sonar.projectKey=gorillaerne
sonar.organization=Gorillaerne

sonar.sources=.
sonar.exclusions=**/*_test.go,**/vendor/**,**/static/**
sonar.tests=.
sonar.test.inclusions=**/*_test.go

sonar.go.coverage.reportPaths=coverage.out

sonar.sourceEncoding=UTF-8
