name: CD

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

env:
  IMAGE: ghcr.io/${{ github.repository_owner }}/go-backend

jobs:
  build-and-push:
    name: Build & Push to GHCR
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build image
        run: |
          docker build \
            -t ${{ env.IMAGE }}:sha-$(git rev-parse --short HEAD) \
            -t ${{ env.IMAGE }}:${{ github.ref_name }} \
            .

      - name: Push image
        run: |
          docker push ${{ env.IMAGE }}:sha-$(git rev-parse --short HEAD)
          docker push ${{ env.IMAGE }}:${{ github.ref_name }}